<?php

namespace elancer;
/* add CPT */
function construct_gametype_cpt(): void {
	add_action( 'init', function () {
		register_post_type( 'edg-game-type', array(
			'labels'              => array(
				'name'                     => 'ChariGame Game Type',
				'singular_name'            => 'ChariGame Game Type',
				'menu_name'                => 'ChariGame Game Type',
				'all_items'                => 'Game Types',
				'edit_item'                => 'Edit ChariGame Game Type',
				'view_item'                => 'View ChariGame Game Type',
				'view_items'               => 'View ChariGame Game Type',
				'add_new_item'             => 'Add New ChariGame Game Type',
				'add_new'                  => 'Add New ChariGame Game Type',
				'new_item'                 => 'New ChariGame Game Type',
				'parent_item_colon'        => 'Parent ChariGame Game Type:',
				'search_items'             => 'Search ChariGame Game Type',
				'not_found'                => 'No edg game type found',
				'not_found_in_trash'       => 'No edg game type found in Trash',
				'archives'                 => 'EDG Game Type Archives',
				'attributes'               => 'EDG Game Type Attributes',
				'insert_into_item'         => 'Insert into edg game type',
				'uploaded_to_this_item'    => 'Uploaded to this edg game type',
				'filter_items_list'        => 'Filter edg game type list',
				'filter_by_date'           => 'Filter edg game type by date',
				'items_list_navigation'    => 'EDG Game Type list navigation',
				'items_list'               => 'EDG Game Type list',
				'item_published'           => 'EDG Game Type published.',
				'item_published_privately' => 'EDG Game Type published privately.',
				'item_reverted_to_draft'   => 'EDG Game Type reverted to draft.',
				'item_scheduled'           => 'EDG Game Type scheduled.',
				'item_updated'             => 'EDG Game Type updated.',
				'item_link'                => 'EDG Game Type Link',
				'item_link_description'    => 'A link to a edg game type.',
			),
			'public'              => true,
			'show_in_menu'        => 'edg-types',
			'exclude_from_search' => true,
			'publicly_queryable'  => false,
			'show_in_nav_menus'   => false,
			'show_in_admin_bar'   => false,
			'show_in_rest'        => false,
			'menu_position'       => 1001,
			'menu_icon'           => 'dashicons-games',
			'supports'            => array(
				0 => 'title',
			),
			'rewrite'             => false,
			'delete_with_user'    => false,
		) );
	} );

	// Add Attributes
	add_action( 'acf/include_fields', function () {
		if ( ! function_exists( 'acf_add_local_field_group' ) ) {
			return;
		}

		acf_add_local_field_group( array(
			'key'                   => 'group_668bb1ef287bc',
			'title'                 => 'EDG Gametype Attributes',
			'fields'                => array(
				array(
					'key'               => 'field_668bb1ef04ec5',
					'label'             => 'Beschreibung',
					'name'              => 'desc',
					'aria-label'        => '',
					'type'              => 'wysiwyg',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'tabs'              => 'all',
					'toolbar'           => 'full',
					'media_upload'      => 1,
					'delay'             => 0,
				),
				array(
					'key' => 'field_67c6e2b966e36',
					'label' => 'How To Play',
					'name' => 'how_to_play_group',
					'aria-label' => '',
					'type' => 'group',
					'instructions' => '',
					'required' => false,
					'conditional_logic' => false,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_67c6e4b88c645',
							'label' => 'How To Play Headline',
							'name' => 'how_to_play_headline',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => false,
							'conditional_logic' => false,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => 'So wird gespielt:',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_67c6e2da66e37',
							'label' => 'How To Play Steps',
							'name' => 'how_to_play_steps',
							'aria-label' => '',
							'type' => 'repeater',
							'instructions' => '',
							'required' => false,
							'conditional_logic' => false,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'row',
							'button_label' => 'Eintrag hinzufügen',
							'rows_per_page' => 20,
							'min' => 0,
							'max' => 0,
							'collapsed' => '',
							'sub_fields' => array(
								array(
									'key' => 'field_67c6e4488c642',
									'label' => 'Step Icon',
									'name' => 'step_icon',
									'aria-label' => '',
									'type' => 'icon_picker',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'tabs' => array(
										0 => 'dashicons',
										1 => 'media_library',
										2 => 'url',
									),
									'return_format' => 'string',
									'allow_in_bindings' => 1,
									'library' => 'all',
									'default_value' => array(
										'type' => NULL,
										'value' => NULL,
									),
									'parent_repeater' => 'field_67c6e2da66e37',
								),
								array(
									'key' => 'field_67c6efc59491c',
									'label' => 'Step Headline',
									'name' => 'step_headline',
									'aria-label' => '',
									'type' => 'textarea',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'allow_in_bindings' => 1,
									'rows' => '',
									'placeholder' => '',
									'new_lines' => '',
									'parent_repeater' => 'field_67c6e2da66e37',
								),
								array(
									'key' => 'field_67c6e49a8c644',
									'label' => 'Step Text',
									'name' => 'step_text',
									'aria-label' => '',
									'type' => 'textarea',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'allow_in_bindings' => 1,
									'rows' => '',
									'placeholder' => '',
									'new_lines' => '',
									'parent_repeater' => 'field_67c6e2da66e37',
								),
								array(
									'key' => 'field_67c6e47a8c643',
									'label' => 'Step Color',
									'name' => 'step_color',
									'aria-label' => '',
									'type' => 'select',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'choices' => array(
										'primary' => 'Primary',
										'secondary' => 'Secondary',
										'teritary' => 'Teritary',
									),
									'default_value' => 'primary',
									'return_format' => 'value',
									'multiple' => 0,
									'allow_null' => 0,
									'allow_in_bindings' => 1,
									'ui' => 0,
									'ajax' => 0,
									'placeholder' => '',
									'parent_repeater' => 'field_67c6e2da66e37',
								),
							),
						),
					),
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'post_type',
						'operator' => '==',
						'value'    => 'edg-game-type',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => '',
			'show_in_rest'          => 0,
		) );
	} );


}


