<?php

namespace elancer;
/* add CPT */
function construct_games_cpt(): void {
	add_action( 'init', function () {

		$menu_title = 'Campaigns';
		$menu_title .= ' <span class="update-plugins"><span class="update-count">' . 1 . '</span></span>';
		register_post_type( 'edg-campaign', array(
			'labels'           => array(
				'name'                     => 'EDG Campaign',
				'singular_name'            => 'EDG Campaign',
				'menu_name'                => 'EDG Campaign',
				//'all_items'                => $menu_title,
				'all_items'                => 'Campaigns',
				'edit_item'                => 'Edit EDG Campaign',
				'view_item'                => 'View EDG Campaign',
				'view_items'               => 'View EDG Campaigns',
				'add_new_item'             => 'Add New EDG Campaign',
				'add_new'                  => 'Add New EDG Campaign',
				'new_item'                 => 'New EDG Campaign',
				'parent_item_colon'        => 'Parent EDG Campaign:',
				'search_items'             => 'Search EDG Campaigns',
				'not_found'                => 'No edg campaign found',
				'not_found_in_trash'       => 'No edg campaign found in Trash',
				'archives'                 => 'EDG Campaign Archives',
				'attributes'               => 'EDG Campaign Attributes',
				'insert_into_item'         => 'Insert into edg campaign',
				'uploaded_to_this_item'    => 'Uploaded to this edg campaign',
				'filter_items_list'        => 'Filter edg campaign list',
				'filter_by_date'           => 'Filter edg campaign by date',
				'items_list_navigation'    => 'EDG Campaign list navigation',
				'items_list'               => 'EDG Campaign list',
				'item_published'           => 'EDG Campaign published.',
				'item_published_privately' => 'EDG Campaign published privately.',
				'item_reverted_to_draft'   => 'EDG Campaign reverted to draft.',
				'item_scheduled'           => 'EDG Campaign scheduled.',
				'item_updated'             => 'EDG Campaign updated.',
				'item_link'                => 'EDG Campaign Link',
				'item_link_description'    => 'A link to a edg campaign.',
			),
			'public'           => true,
			'show_in_menu'     => 'edg-types',
			'show_in_rest'     => false,
			'menu_position'    => 998,
			'menu_icon'        => 'dashicons-games',
			'supports'         => array(
				0 => 'title',
			),
			'rewrite'          => array(
				'slug'       => 'spendenspiel',
				'with_front' => false,
				'pages'      => false,
			),
			'delete_with_user' => false,
		) );
	} );


	// Add Attributes
	add_action( 'acf/include_fields', function () {
		if ( ! function_exists( 'acf_add_local_field_group' ) ) {
			return;
		}
		acf_add_local_field_group( array(
			'key'                   => 'group_65e8519fb8be0',
			'title'                 => 'EDG Campaign Attributes',
			'fields'                => array(
				array(
					'key'                       => 'field_66263e2d9937b',
					'label'                     => 'Active',
					'name'                      => 'active',
					'aria-label'                => '',
					'type'                      => 'checkbox',
					'instructions'              => '',
					'required'                  => 0,
					'conditional_logic'         => 0,
					'wrapper'                   => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'choices'                   => array(
						'active' => 'Active',
					),
					'default_value'             => array(),
					'return_format'             => 'value',
					'allow_custom'              => 0,
					'layout'                    => 'vertical',
					'toggle'                    => 0,
					'save_custom'               => 0,
					'custom_choice_button_text' => 'Add new choice',
				),
				array(
					'key'               => 'field_6697a3d24f8d6',
					'label'             => 'Game Form Gruppe',
					'name'              => 'game_form_gruppe',
					'aria-label'        => '',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'block',
					'sub_fields'        => array(
						array(
							'key'               => 'field_66670d828a6be',
							'label'             => 'Kampagnen Titel',
							'name'              => 'campaign_title',
							'aria-label'        => '',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'maxlength'         => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
						),
						array(
							'key'               => 'field_6697a42f4f8d7',
							'label'             => 'Kampagnen Beschreibungstext',
							'name'              => 'campaign_desc_text',
							'aria-label'        => '',
							'type'              => 'wysiwyg',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'tabs'              => 'all',
							'toolbar'           => 'full',
							'media_upload'      => 1,
							'delay'             => 0,
						),
					),
				),
				array(
					'key'               => 'field_65e8519f0abcf',
					'label'             => 'Game Type',
					'name'              => 'game_type',
					'aria-label'        => '',
					'type'              => 'select',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'choices'           => array(
						999999 => 'Tower-Blocks',
						999998   => 'Memory',
					),
					'default_value'     => false,
					'return_format'     => 'value',
					'multiple'          => 0,
					'allow_null'        => 0,
					'ui'                => 0,
					'ajax'              => 0,
					'placeholder'       => '',
				),
				array(
					'key'               => 'field_66670a432bfa9',
					'label'             => 'Memory-Einstellungen',
					'name'              => 'memory_settings',
					'aria-label'        => '',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'field_65e8519f0abcf',
								'operator' => '==',
								'value'    => '999998',
							),
						),
					),
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'block',
					'sub_fields'        => array(
						array(
							'key'               => 'field_66670a7e2bfaa',
							'label'             => 'Memory Grid',
							'name'              => 'memory_grid',
							'aria-label'        => '',
							'type'              => 'range',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => 0,
							'min'               => '',
							'max'               => 4,
							'step'              => 2,
							'prepend'           => '',
							'append'            => '',
						),
						array(
							'key'               => 'field_66670ab72bfab',
							'label'             => 'Memory Images',
							'name'              => 'memory_images',
							'aria-label'        => '',
							'type'              => 'gallery',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'return_format'     => 'url',
							'library'           => 'all',
							'min'               => 9,
							'max'               => 9,
							'min_width'         => '',
							'min_height'        => '',
							'min_size'          => '',
							'max_width'         => '',
							'max_height'        => '',
							'max_size'          => '',
							'mime_types'        => '',
							'insert'            => 'append',
							'preview_size'      => 'medium',
						),
					),
				),
				array(
					'key'               => 'field_65f87108461e2',
					'label'             => 'Recipient 1',
					'name'              => 'recipient_1',
					'aria-label'        => '',
					'type'              => 'select',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'choices'           => array(
//						305 => 'Rettet den Regenwald',
//						137 => 'Mission Erde e.V.',
//						136 => 'David Sheldrick Wildlife Trust',
//						134 => 'Stiftung Wilderness International',
					),
					'default_value'     => false,
					'return_format'     => 'value',
					'multiple'          => 0,
					'allow_null'        => 0,
					'ui'                => 0,
					'ajax'              => 0,
					'placeholder'       => '',
				),
				array(
					'key'               => 'field_65f876858bbda',
					'label'             => 'Recipient 2',
					'name'              => 'recipient_2',
					'aria-label'        => '',
					'type'              => 'select',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'choices'           => array(
//						305 => 'Rettet den Regenwald',
//						137 => 'Mission Erde e.V.',
//						136 => 'David Sheldrick Wildlife Trust',
//						134 => 'Stiftung Wilderness International',
					),
					'default_value'     => false,
					'return_format'     => 'value',
					'multiple'          => 0,
					'allow_null'        => 0,
					'ui'                => 0,
					'ajax'              => 0,
					'placeholder'       => '',
				),
				array(
					'key'               => 'field_65f8768d8bbdb',
					'label'             => 'Recipient 3',
					'name'              => 'recipient_3',
					'aria-label'        => '',
					'type'              => 'select',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'choices'           => array(
//						305 => 'Rettet den Regenwald',
//						137 => 'Mission Erde e.V.',
//						136 => 'David Sheldrick Wildlife Trust',
//						134 => 'Stiftung Wilderness International',
					),
					'default_value'     => false,
					'return_format'     => 'value',
					'multiple'          => 0,
					'allow_null'        => 0,
					'ui'                => 0,
					'ajax'              => 0,
					'placeholder'       => '',
				),
				array(
					'key'               => 'field_668c2bb89857b',
					'label'             => 'Spendenverteilung Gruppe',
					'name'              => 'spendenverteilung_gruppe',
					'aria-label'        => '',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'block',
					'sub_fields'        => array(
						array(
							'key'               => 'field_66b1d2d3649a2',
							'label'             => 'Highscore',
							'name'              => 'highscore',
							'aria-label'        => '',
							'type'              => 'true_false',
							'instructions'      => 'Bitte geben Sie an, ob möglichst wenig oder möglichst viele Punkte erreicht werden sollen.',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'message'           => '',
							'default_value'     => 0,
							'ui_on_text'        => 'Möglichst wenig',
							'ui_off_text'       => 'Möglichst viel',
							'ui'                => 1,
						),
						array(
							'key'               => 'field_66b1d323649a3',
							'label'             => 'Gewinnkategorie',
							'name'              => 'gewinnkategorie',
							'aria-label'        => '',
							'type'              => 'repeater',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'layout'            => 'table',
							'pagination'        => 0,
							'min'               => 0,
							'max'               => 0,
							'collapsed'         => '',
							'button_label'      => 'Eintrag hinzufügen',
							'rows_per_page'     => 20,
							'sub_fields'        => array(
								array(
									'key'               => 'field_66b1d336649a4',
									'label'             => 'Limit',
									'name'              => 'limit',
									'aria-label'        => '',
									'type'              => 'range',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => '',
									'min'               => '',
									'max'               => '',
									'step'              => '',
									'prepend'           => '',
									'append'            => 'Punkte',
									'parent_repeater'   => 'field_66b1d323649a3',
								),
								array(
									'key'               => 'field_66b1d358649a5',
									'label'             => 'Spendenbetrag',
									'name'              => 'spendenbetrag',
									'aria-label'        => '',
									'type'              => 'number',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => '',
									'min'               => '',
									'max'               => '',
									'placeholder'       => '',
									'step'              => '',
									'prepend'           => '',
									'append'            => 'in €',
									'parent_repeater'   => 'field_66b1d323649a3',
								),
							),
						),
					),
				),
				array(
					'key' => 'field_67d955de0335e',
					'label' => 'Spendentopf Initial',
					'name' => 'spendentopf_initial',
					'aria-label' => '',
					'type' => 'range',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 0,
					'min' => '',
					'max' => 10000,
					'allow_in_bindings' => 0,
					'step' => '',
					'prepend' => '',
					'append' => 'in €',
				),
				array(
					'key'               => 'field_6621196731aa8',
					'label'             => 'Dispatch Date Option',
					'name'              => 'dispatch_date_option',
					'aria-label'        => '',
					'type'              => 'radio',
					'instructions'      => 'You can choose to send emails based on either birthdays or dispatch dates',
					'required'          => 1,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'choices'           => array(
						'birthday' => 'Birthday',
						'dispatch' => 'Dispatch Date',
					),
					'default_value'     => 'birthday',
					'return_format'     => 'value',
					'allow_null'        => 0,
					'other_choice'      => 0,
					'layout'            => 'vertical',
					'save_other_choice' => 0,
				),
				array(
					'key'               => 'field_66211ed9d4c8b',
					'label'             => 'Dispatch Date',
					'name'              => 'dispatch_date',
					'aria-label'        => '',
					'type'              => 'date_picker',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'field_6621196731aa8',
								'operator' => '==',
								'value'    => 'dispatch',
							),
						),
					),
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'display_format'    => 'd/m/Y',
					'return_format'     => 'Ymd',
					'first_day'         => 1,
				),
				array(
					'key'               => 'field_6686847953b41',
					'label'             => 'Campaign Start',
					'name'              => 'campaign_start',
					'aria-label'        => '',
					'type'              => 'date_picker',
					'instructions'      => '',
					'required'          => 1,
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'field_6621196731aa8',
								'operator' => '==',
								'value'    => 'birthday',
							),
						),
					),
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'display_format'    => 'd/m/Y',
					'return_format'     => 'Ymd',
					'first_day'         => 1,
				),
				array(
					'key'               => 'field_66211e0531aa9',
					'label'             => 'Dispatch Time',
					'name'              => 'dispatch_time',
					'aria-label'        => '',
					'type'              => 'time_picker',
					'instructions'      => 'Represents the time when the E-Mail is sent to the users',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'display_format'    => 'H:i:s',
					'return_format'     => 'H:i:s',
				),
				array(
					'key'               => 'field_66670b3e2bfac',
					'label'             => 'Gültigkeit der Einladungscodes (in Wochen)',
					'name'              => 'duration',
					'aria-label'        => '',
					'type'              => 'range',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'min'               => 1,
					'max'               => 8,
					'step'              => '',
					'prepend'           => '',
					'append'            => '',
				),
				array(
					'key'               => 'field_666b1e1686f8a',
					'label'             => 'Ende der Kampagne',
					'name'              => 'campaign_end',
					'aria-label'        => '',
					'type'              => 'message',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'message'           => 'Diese Kampagne endet am A um B Uhr',
					'new_lines'         => 'wpautop',
					'esc_html'          => 0,
				),
				array(
					'key'               => 'field_6697ca85969f3',
					'label'             => 'E-Mail Gruppe',
					'name'              => 'email_gruppe',
					'aria-label'        => '',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'block',
					'sub_fields'        => array(
						array(
							'key' => 'field_67fe5e4722e37',
							'label' => 'Ansprache in Mailtext verwenden?',
							'name' => 'address_user',
							'aria-label' => '',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 0,
							'allow_in_bindings' => 0,
							'ui' => 0,
							'ui_on_text' => '',
							'ui_off_text' => '',
						),
						array(
							'key'               => 'field_669f871c56035',
							'label'             => 'E-Mail Betreff',
							'name'              => 'email_subject',
							'aria-label'        => '',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'maxlength'         => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
						),
						array(
							'key'               => 'field_6697cb01969f4',
							'label'             => 'E-Mail Header Image',
							'name'              => 'email_header_image',
							'aria-label'        => '',
							'type'              => 'image',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'return_format'     => 'url',
							'library'           => 'all',
							'min_width'         => '',
							'min_height'        => '',
							'min_size'          => '',
							'max_width'         => '',
							'max_height'        => '',
							'max_size'          => '',
							'mime_types'        => '',
							'preview_size'      => 'medium',
						),
						array(
							'key'               => 'field_6697cb40969f5',
							'label'             => 'E-Mail Headline Claim',
							'name'              => 'email_headline_claim',
							'aria-label'        => '',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'maxlength'         => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
						),
						array(
							'key'               => 'field_6697cb4f969f6',
							'label'             => 'E-Mail Headline',
							'name'              => 'email_headline',
							'aria-label'        => '',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'maxlength'         => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
						),
						array(
							'key'               => 'field_6697cb89969f7',
							'label'             => 'E-Mail Content',
							'name'              => 'email_content',
							'aria-label'        => '',
							'type'              => 'textarea',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'maxlength'         => '',
							'rows'              => '',
							'placeholder'       => '',
							'new_lines'         => '',
						),
						array(
							'key'               => 'field_6697cbd2969f8',
							'label'             => 'E-Mail Signatur',
							'name'              => 'email_signatur',
							'aria-label'        => '',
							'type'              => 'textarea',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'maxlength'         => '',
							'rows'              => '',
							'placeholder'       => '',
							'new_lines'         => '',
						),
						array(
							'key'               => 'field_6697cc70969fa',
							'label'             => 'Social Media Options',
							'name'              => 'social_media_options',
							'aria-label'        => '',
							'type'              => 'repeater',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'layout'            => 'table',
							'pagination'        => 0,
							'min'               => 0,
							'max'               => 0,
							'collapsed'         => '',
							'button_label'      => 'Eintrag hinzufügen',
							'rows_per_page'     => 20,
							'sub_fields'        => array(
								array(
									'key'               => 'field_6697cc8d969fb',
									'label'             => 'Social Media Name',
									'name'              => 'social_media_name',
									'aria-label'        => '',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => '',
									'maxlength'         => '',
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'parent_repeater'   => 'field_6697cc70969fa',
								),
								array(
									'key'               => 'field_6697cd1b969fc',
									'label'             => 'Social Media Link',
									'name'              => 'social_media_link',
									'aria-label'        => '',
									'type'              => 'url',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => '',
									'placeholder'       => '',
									'parent_repeater'   => 'field_6697cc70969fa',
								),
								array(
									'key'               => 'field_6697cd25969fd',
									'label'             => 'Social Media Icon',
									'name'              => 'social_media_icon',
									'aria-label'        => '',
									'type'              => 'image',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'return_format'     => 'url',
									'library'           => 'all',
									'min_width'         => '',
									'min_height'        => '',
									'min_size'          => '',
									'max_width'         => '',
									'max_height'        => '',
									'max_size'          => '',
									'mime_types'        => '',
									'preview_size'      => 'medium',
									'parent_repeater'   => 'field_6697cc70969fa',
								),
							),

						),
					),
				),
				array(
					'key'               => 'field_66b343c2c2f6d',
					'label'             => 'CTAs',
					'name'              => 'ctas',
					'aria-label'        => '',
					'type'              => 'repeater',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'block',
					'pagination'        => 0,
					'min'               => 0,
					'max'               => 0,
					'collapsed'         => '',
					'button_label'      => 'Eintrag hinzufügen',
					'rows_per_page'     => 20,
					'sub_fields'        => array(
						array(
							'key'               => 'field_66b343d3c2f6e',
							'label'             => 'CTA Headline',
							'name'              => 'cta_headline',
							'aria-label'        => '',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'maxlength'         => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'parent_repeater'   => 'field_66b343c2c2f6d',
						),
						array(
							'key'               => 'field_66b343ecc2f6f',
							'label'             => 'CTA Text',
							'name'              => 'cta_text',
							'aria-label'        => '',
							'type'              => 'textarea',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'maxlength'         => '',
							'rows'              => '',
							'placeholder'       => '',
							'new_lines'         => '',
							'parent_repeater'   => 'field_66b343c2c2f6d',
						),
						array(
							'key'               => 'field_66b3440dc2f70',
							'label'             => 'CTA Button Text',
							'name'              => 'cta_button_text',
							'aria-label'        => '',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'maxlength'         => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'parent_repeater'   => 'field_66b343c2c2f6d',
						),
						array(
							'key'               => 'field_66b3442cc2f71',
							'label'             => 'CTA Button Link',
							'name'              => 'cta_button_link',
							'aria-label'        => '',
							'type'              => 'link',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'return_format'     => 'url',
							'parent_repeater'   => 'field_66b343c2c2f6d',
						),
						array(
							'key' => 'field_66fa8e9c13c7e',
							'label' => 'Type',
							'name' => 'type',
							'aria-label' => '',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'primary' => 'Primary',
								'secondary' => 'Secondary',
							),
							'default_value' => 'primary',
							'return_format' => 'value',
							'multiple' => 0,
							'allow_null' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
							'parent_repeater' => 'field_66b343c2c2f6d',
						),
					),
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'post_type',
						'operator' => '==',
						'value'    => 'edg-campaign',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => '',
			'show_in_rest'          => 0,
		) );
	} );

	add_filter( 'acf/load_field/name=campaign_end', 'elancer\modify_campaign_end_message' );
	function modify_campaign_end_message( $field ) {
		$dispatch_date_option = get_field( 'dispatch_date_option', get_the_ID() );
		$dispatch_time_option = get_field( 'dispatch_time', get_the_ID() );
		$campaign_start       = get_field( 'campaign_start', get_the_ID() );
		$dispatch_date        = get_field( 'dispatch_date', get_the_ID() );
		$duration             = get_field( 'duration', get_the_ID() );
		if ( $dispatch_date_option == 'birthday' ) {

			$campaign_end = new \DateTime( $campaign_start );
			$campaign_end->modify( '+1 year' );
			$formatted_date = $campaign_end->format( 'd.m.Y' );

			$field['message'] = sprintf( 'Diese Kampagne endet am <b>%s</b> um <b>%s</b> Uhr', $formatted_date, $dispatch_time_option );

		} else {
			$campaign_end = new \DateTime( $dispatch_date );
			if ( $duration != null ) {
				$campaign_end->modify( '+ ' . $duration . ' weeks' );
			}
			$formatted_date   = $campaign_end->format( 'd.m.Y' );
			$field['message'] = sprintf( 'Diese Kampagne endet am <b>%s</b> um <b>%s</b> Uhr', $formatted_date, $dispatch_time_option );

		}

		return $field;
	}
}

