<?php

namespace elancer;
/* add CPT */
function construct_general_settings(): void {
	add_action( 'acf/init', function () {
		acf_add_options_page( array(
			'page_title'  => 'General Settings',
			'menu_slug'   => 'general-settings',
			'parent_slug' => 'edg-types',
			'menu_title'  => 'General Settings',
			'position'    => 9999,
			'redirect'    => false,
		) );
	} );

	// Add Attributes
	add_action( 'acf/include_fields', function () {
		if ( ! function_exists( 'acf_add_local_field_group' ) ) {
			return;
		}

		acf_add_local_field_group( array(
			'key'                   => 'group_668bdffae61c7',
			'title'                 => 'EDG General Option Attributes',
			'fields'                => array(
				array(
					'key'               => 'field_668bdffb595e0',
					'label'             => 'Login-Form Überschrift',
					'name'              => 'login-form-headline',
					'aria-label'        => '',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'maxlength'         => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
				),
				array(
					'key'               => 'field_668be037595e1',
					'label'             => 'Background Image',
					'name'              => 'background-image',
					'aria-label'        => '',
					'type'              => 'image',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'return_format'     => 'url',
					'library'           => 'all',
					'min_width'         => '',
					'min_height'        => '',
					'min_size'          => '',
					'max_width'         => '',
					'max_height'        => '',
					'max_size'          => '',
					'mime_types'        => '',
					'preview_size'      => 'medium',
				),
				array(
					'key'               => 'field_669f8fd0f6325',
					'label'             => 'Company Settings',
					'name'              => 'company_settings',
					'aria-label'        => '',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'block',
					'sub_fields'        => array(
						array(
							'key'               => 'field_668be06d595e2',
							'label'             => 'Company Logo',
							'name'              => 'company-logo',
							'aria-label'        => '',
							'type'              => 'image',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'return_format'     => 'url',
							'library'           => 'all',
							'min_width'         => '',
							'min_height'        => '',
							'min_size'          => '',
							'max_width'         => '',
							'max_height'        => '',
							'max_size'          => '',
							'mime_types'        => '',
							'preview_size'      => 'medium',
						),
						array(
							'key'               => 'field_669f9481115e5',
							'label'             => 'Company Name',
							'name'              => 'company_name',
							'aria-label'        => '',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'maxlength'         => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
						),
						array(
							'key'               => 'field_669f8feff6326',
							'label'             => 'Company Street',
							'name'              => 'company_street',
							'aria-label'        => '',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'maxlength'         => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
						),
						array(
							'key'               => 'field_669f9022f6327',
							'label'             => 'Company City',
							'name'              => 'company_city',
							'aria-label'        => '',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'maxlength'         => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
						),
						array(
							'key'               => 'field_669f903df6328',
							'label'             => 'Impressum Page',
							'name'              => 'impressum_page',
							'aria-label'        => '',
							'type'              => 'page_link',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'post_type'         => array(
								0 => 'page',
							),
							'post_status'       => '',
							'taxonomy'          => '',
							'allow_archives'    => 1,
							'multiple'          => 0,
							'allow_null'        => 0,
						),
						array(
							'key'               => 'field_669f9077f6329',
							'label'             => 'Datenschutz Page',
							'name'              => 'datenschutz_page',
							'aria-label'        => '',
							'type'              => 'page_link',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'post_type'         => array(
								0 => 'page',
							),
							'post_status'       => '',
							'taxonomy'          => '',
							'allow_archives'    => 1,
							'multiple'          => 0,
							'allow_null'        => 0,
						),
						array(
							'key'               => 'field_669f9092f632a',
							'label'             => 'AGB Page',
							'name'              => 'agb_page',
							'aria-label'        => '',
							'type'              => 'page_link',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'post_type'         => '',
							'post_status'       => '',
							'taxonomy'          => '',
							'allow_archives'    => 1,
							'multiple'          => 0,
							'allow_null'        => 1,
						),
					),
				),
				array(
					'key'               => 'field_668be082595e3',
					'label'             => 'Primary Color',
					'name'              => 'primary-color',
					'aria-label'        => '',
					'type'              => 'color_picker',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'enable_opacity'    => 0,
					'return_format'     => 'string',
				),
				array(
					'key'               => 'field_668be097595e4',
					'label'             => 'Secondary Color',
					'name'              => 'secondary-color',
					'aria-label'        => '',
					'type'              => 'color_picker',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'enable_opacity'    => 0,
					'return_format'     => 'string',
				),
				array(
					'key' => 'field_67c6a69b2d5aa',
					'label' => 'Teritary Color',
					'name' => 'teritary-color',
					'aria-label' => '',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'enable_opacity' => 0,
					'return_format' => 'string',
				),
				array(
					'key'               => 'field_668be955af39a',
					'label'             => 'Section Primary',
					'name'              => 'section-primary',
					'aria-label'        => '',
					'type'              => 'image',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'return_format'     => 'url',
					'library'           => 'all',
					'min_width'         => '',
					'min_height'        => '',
					'min_size'          => '',
					'max_width'         => '',
					'max_height'        => '',
					'max_size'          => '',
					'mime_types'        => '',
					'preview_size'      => 'medium',
				),
				array(
					'key'               => 'field_668be972af39b',
					'label'             => 'Section Secondary',
					'name'              => 'section-secondary',
					'aria-label'        => '',
					'type'              => 'image',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'return_format'     => 'url',
					'library'           => 'all',
					'min_width'         => '',
					'min_height'        => '',
					'min_size'          => '',
					'max_width'         => '',
					'max_height'        => '',
					'max_size'          => '',
					'mime_types'        => '',
					'preview_size'      => 'medium',
				),
				array(
					'key'               => 'field_668bed1fa3568',
					'label'             => 'Video Mp4',
					'name'              => 'video-mp4',
					'aria-label'        => '',
					'type'              => 'file',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'return_format'     => 'url',
					'library'           => 'all',
					'min_size'          => '',
					'max_size'          => '',
					'mime_types'        => '',
				),
				array(
					'key'               => 'field_6697961a56c02',
					'label'             => 'Main-Font',
					'name'              => 'main-font',
					'aria-label'        => '',
					'type'              => 'file',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'return_format'     => 'url',
					'library'           => 'all',
					'min_size'          => '',
					'max_size'          => '',
					'mime_types'        => '',
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'options_page',
						'operator' => '==',
						'value'    => 'general-settings',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => '',
			'show_in_rest'          => 0,
		) );
	} );
}

